### ISSUE TITLE
Lageplan-Navigation

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#120]
Der Lageplan soll eine Navigationsfunktion bieten. Dazu läuft eine Masterarbeit bei Dr. Anne Tauch, die sich voraussichtlich bei Ulrike Lucke melden wird.

**Comment by alekiy** [comment]
Ist im Sand verlaufen. Keine Rückmeldung mehr erhalten.
Closes due to inactivity.
