### ISSUE TITLE
Lagepläne - Ladezeit

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#220]
- [ ] Laden dauert trotz wlan mehr als 30s, vorher weiße Fläche, IMplementierung eines Progress Indicators
- [ ] Caching? Nach einem Neustart der app dauert es wieder eine kleine Ewigkeit, bis was kommt. 
- [ ] Wenn man das Handy dreht, ist wieder lange Zeit nichts zu sehen; Das erwartet man so nicht; Zurückdrehen hilft auch nicht. (Evt. muss die Unterstützung fürs auto.-Drehen disabled werden?)
- [ ] Scroll und zoom geht nicht; Es ist immer ein mehr oder weniger nichtssagender Ausschnitt sichtbar; Beispiel:
- [ ] 3.5. Die Freitextsuche scheint irgendwie unpraktisch, bzw. ich kann kaum eine nützliches Szenario finden. Evt. fehlt mir dafür aber die "richtige" Perspektive.
  Beispiel: Suche auf Map Griebnitzsee nach "Hörsaalgebäude" oder "Hörsaal" tut irgendwie nicht das, was man dann brauchen könnte.

![image](https://cloud.githubusercontent.com/assets/2682987/4332031/2f0f5b22-3fce-11e4-9b34-aed1709b0df8.png)

**Comment by ItsNotYou** [comment]
Betrifft möglicherweise #491

**Comment by lkstnr** [comment]
https://github.com/University-of-Potsdam-MM/Mobile.UP/issues/630
