### ISSUE TITLE
Backbone.Router PushState Refactoring

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#275]
Backbone Router mit PushState refactorn und Ansichten Router-fähig machen
- [x] Moodle
- [x] Bibliothekssuche
- [ ] PULS
  siehe #217

Code für Router der Initialisierung

```
Backbone.history.start({pushState: true});
approuter.navigate('#home', true);
```

**Comment by ItsNotYou** [comment]
Bibliothekssuche ist mit #134 gelöst.

**Comment by alekiy** [comment]
Nur noch PULS ausstehend.

**Comment by alekiy** [comment]
Ist für neue Version nicht mehr relevant.
