### ISSUE TITLE
Moodle-Übungen manuell zu Stundenplan hinzufügen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#297]
Es wäre gut wenn man die Übungen, zu denen man sich über Moodle anmeldet separat in der App zu dem Stundenplan hinzufügen könnte! (Mail vom 20.10.2014 10:58)

**Comment by ItsNotYou** [comment]
Einige Kurse lassen sich, abhängig vom Institut, generell nicht per PULS belegen, u.a. bei uns in den Kulturwissenschaften. Da sie deshalb nicht im Stundenplan der App angezeigt werden, fände ich es toll, wenn man selbst Kurse für den eigenen Stundenplan anlegen könnte (incl. Raumnummer und Lehrkraft). Da ich im Zweifachbachelor studiere, werden mir meine Zweitfachkurse und Schlüsselkompetenzenkurse angezeigt, jedoch nicht die für mein Erstfach, was etwas verwirrend ist. Schön wäre es, alle Kurse in einem Stundenplan angezeigt zu bekommen. (Mail vom 19.10.2015 16:10)

**Comment by lkstnr** [comment]
Duplicate https://github.com/University-of-Potsdam-MM/Mobile.UP/issues/537
