### ISSUE TITLE
Reload-Option for ErrorView

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#304]
Sofern ein Fehler beim Laden auftritt wäre es hilfreich sofern es eine Art 'refresh' gäbe um den Request erneut abzusetzen.

Folgende Views arbeiten mit der ErrorView und qualifizieren sich damit für einen Reload:
- [x] CalendarSelectionPageView
- [x] CalendarPage (2x)
- [ ] EventsView
- [ ] EventsPlace
- [ ] GradesPage
- [ ] LectureSingleCourseView
- [ ] LecturesPage
- [ ] MensaPage
- [ ] MoodleApp.CourseView
- [ ] MoodlePage (2x)
- [ ] PeoplePage (3x)
- [ ] RoomsOverview
- [ ] CampusMapView
- [ ] SitemapIndex
- [ ] TransportStations

Folgende Models (auweia!):
- [ ] App.model.Book
- [ ] App.model.LibrarySearch

Möglicherweise von der VBB-Rest-Umstellung betroffen:
- [ ] TransportStations
- [ ] Connection
- [ ] getVerbindung
- [ ] getExternalId

**Comment by ItsNotYou** [comment]
Folgende Views arbeiten mit der ErrorView und qualifizieren sich damit für einen Reload:
- [ ] CalendarSelectionPageView
- [ ] CalendarPage (2x)
- [ ] EventsView
- [ ] EventsPlace
- [ ] GradesPage
- [ ] LectureSingleCourseView
- [ ] LecturesPage
- [ ] MensaPage
- [ ] MoodleApp.CourseView
- [ ] MoodlePage (2x)
- [ ] PeoplePage (3x)
- [ ] RoomsOverview
- [ ] CampusMapView
- [ ] SitemapIndex
- [ ] TransportStations

Folgende Models (auweia!):
- [ ] App.model.Book
- [ ] App.model.LibrarySearch

Möglicherweise von der VBB-Rest-Umstellung betroffen:
- [ ] TransportStations
- [ ] Connection
- [ ] getVerbindung
- [ ] getExternalId
