### ISSUE TITLE
Logout-Button :hover / :focus

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#315]
Oben der Logout-Button zeigt nur das Ausschaltensymbol, wenn man die App startet und eingeloggt ist, nicht aber das Wort "Logout" dahinter. Erst wenn man navigiert oder Logout drückt, erscheint das Wort. Wahrscheinlich irgendein :hover oder :focus Problem. (Sieht sehr komisch und kaputt aus).

**Comment by ItsNotYou** [comment]
Habe ich nicht mehr gefunden.
