### ISSUE TITLE
Moodle öffnet keine PDFs

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#337]
MP3s werden abgespielt, für MIDIs und PDFs sollte sich ein Auswahlfenster öffnen. Stattdessen bleibt der InAppBrowser leer.

**Comment by ItsNotYou** [comment]
@alekiy Lassen wir das so, bis die Login-Struktur verändert ist?

**Comment by alekiy** [comment]
Wenn es so ist wie beim letzten mal wo ichs gesehen habe, dann ja.

**Comment by ItsNotYou** [comment]
Weitere Entwicklungen werden zurückgestellt, bis die SSO-Umgebung für Moodle implementiert ist.

**Comment by alekiy** [comment]
Mit der Umstellung auf die App wird es nicht weiterverfolgt.
