### ISSUE TITLE
Feedback-Möglichkeit einbauen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#372]
Ticket#2014120410000211
"Ihr könntet ins Menü direkt eine Möglichkeit integrieren euch Feedback zu geben. Haben andere Apps auch, dann muss man nicht extra die Mail aus dem Impressum suchen, zumal ihr euch dann gleich essentielle Infos automatisch mitschicken lassen könntet."

**Comment by alekiy** [comment]
- https://github.com/pushandplay/cordova-plugin-apprate


![image](https://user-images.githubusercontent.com/2682987/52325894-059efb00-29e7-11e9-94ac-0dc1e4922fab.png)

**Comment by alekiy** [comment]
@lkstnr Vorschläge wie wir das Feedback versenden? An einen Rest-Service der die dann per Mail weiterschickt?

**Comment by lkstnr** [comment]
@alekiy Ja, erscheint mir sinnvoll. Eventuell können wir optional bestimmte Informationen mitsenden (Betriebssystem, App-Version, ...), falls es sich um einen Bug-Report handelt.

**Comment by alekiy** [comment]
@lkstnr & @weihmann Nun dürft ihr euch wünschen was wir speichern wollen:

- Betriebssystem
- App-Version
- UUID?
- Anonymisiert (ja / nein-> uid)
- Feedback
- Recommendation-Value (1-10)
- Bewertung (1-5)

**Comment by lkstnr** [comment]
Bringt uns die UUID etwas? Ich würde es sonst schon anonymisieren. Alles andere speichern.

**Comment by alekiy** [comment]
Wir könnten es dem Nutzer überlassen ob anonym oder nicht. Dann hätten wir gleich ein Feedback-Kanal über Mail :p 
Bringt uns dann ggf. Studiengang oder sonst was?

**Comment by weihmann** [comment]
Mit der UUID könnte man hier nur nachvollziehen, ob jemand, der eine schlechte Bewertung gibt, oft Fehler hatte. Aber denke nicht, dass das so viel bringt.
Man könnte vielleicht den Nutzer selber mit Checkboxen wählen lassen, was er gerne senden würde? (opt-in)
Andernfalls wäre die Wahl "anonym" oder "nicht anonym" wahrscheinlich am sinnvollsten.

Wüsste nicht, was der Studiengag bringen sollte. Welche statistisch relevanten Aussagen könnte man damit treffen?

**Comment by alekiy** [comment]
- [ ] LoggingAPI wird erweitert um Feedback-Funktion
