### ISSUE TITLE
Nudeltheke Golm mit aufnehmen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#374]
Ticket#2014120210000456
"Wusstet ihr übrigens, dass Golm seit diesem SM auch über eine Nudeltheke verfügt? Aber wahrscheinlich bezieht ihr eure Infos aus dem Internet (Studentenwerk Potsdam?), wo die Nudeltheke afaik (noch?) nicht aufgelistet wird."

**Comment by ItsNotYou** [comment]
Prüfen, ob die Nudeltheke inzwischen aufgenommen ist.

**Comment by ItsNotYou** [comment]
Angebot sollte eigentlich freigeschaltet sein, erscheint aber nicht in der XML. Kommunikation mit Gottschlich erforderlich.

**Comment by ItsNotYou** [comment]
Lässt sich in der vorlesungsfreien Zeit nicht prüfen

**Comment by alekiy** [comment]
Prüfen sollte angeblich im neuen Auszug drin sein.

**Comment by alekiy** [comment]
Weiterhin im Auszug nicht vorhanden.

**Comment by alekiy** [comment]
Mit Umstieg auf neue Schnittstelle erledigt.
