### ISSUE TITLE
Logout-Icon fehlt unter Android 2.3.6

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#388]
Getestet auf Julians Smartphone.
![sc20141208-143631](https://cloud.githubusercontent.com/assets/1041388/5360500/2a344e5a-7fc5-11e4-8575-877234093223.png)

**Comment by Clickmari** [comment]
isset jetze besser?

**Comment by ItsNotYou** [comment]
- [ ] Im Desktop-Browser ist das Logo krümmelig und zu dünn.
![desktop](https://cloud.githubusercontent.com/assets/1041388/6690111/af9e705c-ccbe-11e4-84e0-7fb32c32090a.png)
- [ ] Auf dem S4 auch.
![s4-main](https://cloud.githubusercontent.com/assets/1041388/6690110/af9d30de-ccbe-11e4-8bee-8cd36ae43d2c.png)
- [ ] In Untermenüs ist das Icon immer noch größer als im Hauptmenü.
![s4-sub](https://cloud.githubusercontent.com/assets/1041388/6690112/af9f6408-ccbe-11e4-9412-12b40ca86654.png)

**Comment by Clickmari** [comment]
isset besser?

**Comment by ItsNotYou** [comment]
@Clickmari Nur der erste Punkt ist besser, die anderen beiden (S4 krümelig und S4 Untermenü größer) bestehen nach wie vor.

**Comment by Clickmari** [comment]
besser???

**Comment by ItsNotYou** [comment]
![header_overlay](https://cloud.githubusercontent.com/assets/1041388/11220998/0335c570-8d63-11e5-88cd-b38f1f96b87a.png)
Besser aber nicht gut genug.

**Comment by ItsNotYou** [comment]
![2016-10-04 19 18 36](https://cloud.githubusercontent.com/assets/1041388/19088892/7704d744-8a78-11e6-9261-bfc449e72cb5.png)
Gut genug.
