### ISSUE TITLE
Weniger Fehler bei PULS anzeigen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#408]
Gecachte Daten verwenden und nicht den ganzen Bildschirm mit der Fehlermeldung füllen. Betrifft alle PULS-verwendenden Features.
- [ ] Calendar
- [ ] Leistungen
- [ ] Vorlesungsverzeichnis

**Comment by alekiy** [comment]
@ItsNotYou Ist das noch aktuell oder bereits erledigt?
Welche Funktionen betrifft das noch?

**Comment by ItsNotYou** [comment]
Nächste Schritte PULS-API-Code aus Leistungen extrahieren und in den anderen beiden Modulen verwenden. Fehler-Erkennung im PULS-API-Code regeln und das Fehler-Handling in allen Modulen vereinheitlichen.

**Comment by alekiy** [comment]
Wurde in der neuen Version umgesetzt und die Funktionen als PULS-Provider gekapselt.
