### ISSUE TITLE
Campus Maulbeerallee einbauen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#410]
Ticket#2015022310001085:
"Ich finde die app super, aber bei der Raumbelegung und den Verkehrsverbindungen wäre es super wenn der Campus Maulbeerallee auch berücksichtigt würde."
- [ ] Raumbelegung
- [ ] Lagepläne
- [x] Bus & Bahn

**Comment by alekiy** [comment]
Vorarbeiten abgeschlossen

**Comment by alekiy** [comment]
@lkstnr Erst einmal prüfen wie wir den Campus-Tab dann erweitern könnten. Es gibt nämlich noch mehr Standorte wie bspw. Pirschheide oder den Hauptbahnhof in Zukunft.
