### ISSUE TITLE
Moodle-Ansicht zeigt Kurse des vorherigen Nutzers

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#415]
Wenn die Moodle-Ansicht mit Nutzer A geöffnet wird, dieser sich anschließend ausloggt und Nutzer B eingeloggt auf die Moodle-Ansicht geht, werden immer noch die Kurse von Nutzer A angezeigt.

**Comment by alekiy** [comment]
Funktion nicht länger vorhanden.
