### ISSUE TITLE
Moodle-Übersicht zeigt Semester nicht an

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#435]
Damit fehlt eine wichtige Orientierungsmöglichkeit bei gleichlautenden Kursen.

**Comment by jonnyBlu** [comment]
In meiner Moodle-Kurs-Ansicht kann ich auch nicht sehen um welches Semester es sich bei welchem Kurs handelt...

![moodle-kursansicht](https://cloud.githubusercontent.com/assets/1726293/8205246/38cb3afe-14ef-11e5-9bbd-6f5d06485353.png)

**Comment by ItsNotYou** [comment]
#434 ist wichtiger, dieses hier kann zurückgestellt werden.
