### ISSUE TITLE
Moodle-externe URLs außerhalb der App öffnen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#436]
Ein Moodle-Kurs kann Verlinkungen enthalten, die nicht auf ein Ziel innerhalb von Moodle, sondern auf eine externe Seite wie PEP verweisen. In diesem Fall ist es komfortabler, diese Seiten im Systembrowser statt im InApp-Browser zu betrachten.

**Comment by alekiy** [comment]
Mit der Umstellung auf die App wird es nicht weiterverfolgt.
