### ISSUE TITLE
Stundenplan unterstützt nicht alle Veranstaltungsrhythmen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#437]
Das Vorlesungsverzeichnis unter https://puls.uni-potsdam.de/QIS/VVZ/20151/VVZ_96335.pdf listet auf Seite vier ganze 16 Veranstaltungsrhythmen auf, von denen wir derzeit vier unterstützen. Was machen wir mit den anderen?

**UPDATE**
Demnach müssen wir drei Rhythmen implementieren:
- [x] Block
- [x] Block (inkl. Sa)
- [x] Block (inkl. Sa,So)

**Comment by ItsNotYou** [comment]
Entscheidung: Es wird ein Hook eingebaut, der unbekannte Veranstaltungsrhythmen sowie den dazugehörigen Titel an ein externes Log sendet, damit wir wissen, wie viele und welche Veranstaltungen betroffen sind.

**Comment by ItsNotYou** [comment]
Wir werden das Log eine Weile beobachten und dann entscheiden, wie es weiter geht.

**Comment by ItsNotYou** [comment]
Wir haben
* Block
  * 11 Spanisch Propädeutikum I
  * 2160 Immuntechnologie
  * 22441 UNIcert I/1 Italienisch
  * 22492 UNIcert I/2 Spanisch
  * 260521 Planung und Gestaltung von Englischunterricht
  * 4231 Paläoklimadynamik
  * 841531 Seminar und Praktikum in pädagogisch-psychologischen Handlungsfeldern (PppH)
  * 843921 Sprachentwicklung und -förderung von Kindern mit Deutsch als Zweitsprache
  * Latein für Anglisten und Romanisten
  * Polnisch Propädeutikum
* Block (inkl. Sa)
  * 22461 UNIcert I/1 Portugiesisch
* Block (inkl. Sa,So)
  * 1240 Versuchsplanung
  * 2128 Ski nordisch
  * 2136 Schneesport

**Comment by alekiy** [comment]
Noch relevant?

**Comment by ItsNotYou** [comment]
Ist noch relevant. Unten ein Auszug der Daten, die seit Dezember 2016 relevant waren. Demnach müssen wir drei Rhythmen implementieren:
- Block
- Block (inkl. Sa)
- Block (inkl. Sa,So)

Ich passe das Ticket dementsprechend an.

|course|rhythm|last request|
|-------|--------|-------------|
|GIS und FEcolon;Methoden und Techniken|Block|2017-02-13 12:08:19|
|Seminar und Praktikum in pädagogisch-psychologischen Handlungsfeldern (PppH)|Block|2017-02-08 09:31:59|
|UNIcert I/2 Französisch|Block|2017-02-07 14:00:23|
|Aquafitness|Block (inkl. Sa,So)|2017-01-25 19:16:28|
|UNIcert I/1 Italienisch|Block|2017-01-23 16:02:13|
|5001 Regierungskommunikation 2.0 mit den Strukturen öffentlicher Verwaltung|Block (inkl. Sa)|2017-01-21 09:11:34|
|Hochbegabte erkennen und in Regelklassen fördern|Block (inkl. Sa)|2017-01-20 11:00:21|
|23011 Office kompakt (Word, PowerPoint, Excel)|Block|2017-01-17 11:56:41|
|Fallarbeit und individuelle Förderplanung (FS Sprache)|Block (inkl. Sa)|2017-01-09 11:44:49|
|Interkulturell denken und handeln|Block (inkl. Sa,So)|2017-01-05 12:57:38|
|Bioinformatik biologischer Sequenzen / Evolutionary Genomics|Block|2017-01-05 11:59:46|
|MMPP03 Fortgeschrittene Petrologie und Geochemie I|Block|2017-01-04 15:07:46|
|UNIcert I/1 Polnisch|Block (inkl. Sa)|2017-01-02 23:25:24|
|Current Problems and Modern Methods in Plant Genetics and Epigenetics|Block|2017-01-02 22:20:03|
|MGEP05 Sedimentäre Becken|Block|2017-01-02 19:23:33|
|UNIcert I/1 Portugiesisch|Block|2017-01-02 16:55:22|
|BScP01 Geowissenschaften I|Block|2017-01-01 19:06:28|
|Immuntechnologie|Block|2016-12-29 00:11:38|
|Fachdidaktisches Tagespraktikum im Bereich Rezeption und Produktion von Texten|Block|2016-12-28 14:19:49|
|Schneesport|Block (inkl. Sa,So)|2016-12-25 18:44:12|
|Förderung der Bildungssprache Deutsch in allen Fächern|Block (inkl. Sa)|2016-12-25 16:54:26|
|Ski nordisch|Block (inkl. Sa,So)|2016-12-24 15:43:36|
|UNIcert I/2 Spanisch|Block|2016-12-22 22:36:49|
|Praktikum Organische Chemie für BLAC10 (GMB3)|Block|2016-12-21 11:46:56|
|Spanisch Propädeutikum II|Block|2016-12-21 11:09:55|
|MGEW13 Paläoklimadynamik|Block|2016-12-17 18:28:47|
|Schulsport Winterolympiade|Block (inkl. Sa,So)|2016-12-17 17:53:17|
|Praktikum Physik 1 zu Modul BBW 2010-1.02|Block|2016-12-17 14:17:07|
|UNIcert I/1 Französisch|Block|2016-12-16 15:04:42|
|Developmental Biology of Animals and Plants|Block|2016-12-16 10:21:20|
|Empirische Forschung 2|Block (inkl. Sa)|2016-12-16 09:38:43|
|Bullying in der Schulecolon; Erkennen, Handeln, Vorbeugen|Block (inkl. Sa)|2016-12-16 09:25:10|
|UNIcert I/1 Italienisch|Block (inkl. Sa)|2016-12-15 18:04:04|
|Beratung im schulischen Kontext|Block (inkl. Sa)|2016-12-15 17:55:08|
|Planung und Gestaltung von Englischunterricht (Sekundarstufe)|Block|2016-12-15 11:48:41|
|Spanisch Propädeutikum I|Block|2016-12-15 09:41:43|
|423111 Menschenrechte, Frauenrechte, Flüchtlingsrechtecolon; Normativität und Faktizität (LP Teil 2)|Block (inkl. Sa)|2016-12-14 16:11:46|
|Selbstreflexion und Planung für Religionswissenschaft, Jüdische Studien und Jüdische Theologie|Block|2016-12-14 09:54:03|
|Toxicology I - seminar|Block|2016-12-12 10:23:21|
|Toxicology I - research intership|Block|2016-12-12 10:23:20|
|Utopian States of America|Block (inkl. Sa,So)|2016-12-08 13:56:51|
|Diversität im Klassenzimmer|Block (inkl. Sa)|2016-12-08 07:25:34|
|Studien zur Chromosomenstruktur und -funktion und ihre Anwendungen in der Pflanzenbiotechnologie|Block|2016-12-07 00:50:53|
|Fachdidaktisches Tagespraktikum und Begleitseminar|Block|2016-12-05 11:53:18|
|Einführung in Kodikologie und Paläografie|Block|2016-12-05 10:49:13|
|Alter(n)sgerechte Arbeitsgestaltung als Bildungsproblem im Lebenslaufcolon; Konzepte, Modelle und Instrumente|Block (inkl. Sa)|2016-12-05 10:07:19|
|Physische Geographie Seminar|Block|2016-12-03 17:30:10|
|ldquo;Kopfkinoldquo; ndash; akustische Erfahrbarkeit interkultureller Kontexte|Block (inkl. Sa,So)|2016-12-03 10:24:00|
|Historische Modelle des Schulsports|Block (inkl. Sa,So)|2016-12-02 10:42:26|
|bdquo;Wie verstehen wir, was wir da lesen?ldquo; ndash; Schriftverständnisse bei Juden, Christen und Muslimen|Block|2016-12-02 10:02:11|
|Neue Globalisierungsdiskurse|Block (inkl. Sa)|2016-12-01 08:09:33|
