### ISSUE TITLE
Download von Moodle-Ordnerinhalten funktioniert nicht

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#438]
Moodle-Kurse bieten Ordner, aus denen Inhalte heruntergeladen werden können. Zumindest im Moodle-Kurs zum Projekt Fides funktioniert dieser Download nicht.

**Comment by alekiy** [comment]
Mit der Umstellung auf die App wird es nicht weiterverfolgt.
