### ISSUE TITLE
Was passiert mit Branch responsive

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#449]
@Clickmari Der Branch responsive hatte seinen letzten Commit 990df86c07a12480143ee2c80b901e28376221e0 vor einem Jahr. Allerdings ist ein Commit auf dem Branch nicht in den master gemerged. Haben wir noch Pläne dafür oder kann der Branch responsive gelöscht werden?

**Comment by Clickmari** [comment]
puuuhhh....nee, eigentlich muss das noch gemacht werden fuer so tablets. bedauerlicher weise hab ich aber grad keine zeit..lass den branch mal da. nicht mergen. ich muss erstmal schauen.

**Comment by ItsNotYou** [comment]
@Clickmari hat sich etwas verändert?

**Comment by Clickmari** [comment]
Soweit ich mich erinnere ist das Problem, dass die App sich nicht mit-orientiert, wenn man sein Tablet rumdreht (landscape). Da wäre dann ja theoretisch auf der linken Seite Platz, um das Hauptmenu von der Startseite einfach drin zu behalten, vielleicht so zum raus fahren ;). Andererseits finde ich das nicht mehr so nötig, weil wir glaube ich die Navigationsstruktur eh mit der Zeit verflacht (das Wort gibt's ab jetzt...) haben. Schließ den branch, da ist auf keinen Fall irgendetwas wichtiges drin, hat ja jetzt zwei Jahre niemand was gebraucht ;)
