### ISSUE TITLE
Personensuche mit mehr als zwei Buchstaben liefert nur exakte Treffer

### ISSUE THREAD

**Issue by jonnyBlu** [University-of-Potsdam-MM/Mobile.UP#451]
Wenn ich z.B. nach 'a', oder 'al' suche bekomme ich alle Ergebnisse in denen ein 'a' oder die Zeichenfolge 'al' vorkommen. 
Suche ich allerdings nach 'ale' oder 'alex' werden mir keine Ergebnisse geliefert.

**Comment by alekiy** [comment]
Fehler wurde behoben.
