### ISSUE TITLE
goFIT

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#463]
Der studentische Fitnessclub goFit in Golm fehlt in der Übersichtskarte. http://www.hochschulsport-potsdam.de/cgi/webpage.cgi?spid=4327fd0105c4af404e59c82afce59a7d

**Comment by alekiy** [comment]
Bitte den Club noch einfügen.

**Comment by alekiy** [comment]
@PhilippJakupovic Da haste gleich die nächste Aufgabe. ;)
