### ISSUE TITLE
Inhaltsstoffe anzeigen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#481]
"es wäre für mich und viele, die ich kenne, ein großer Gewinn, wenn in der APP die Zusatzstoffe der Mahlzeiten angezeigt würden." Ticket#2016012710000677

**Comment by alekiy** [comment]
Hr. Gottschlich will dies bis Ende Januar zur Verfügung stellen.

**Comment by ItsNotYou** [comment]
@alekiy fragt nach

**Comment by alekiy** [comment]
Zusatzsstoffe sind enthalten.
Achtung es gibt allergens und additives. Dabei werden Sie in der Liste zum Anzeigen Groß geschrieben und in der Aufzählung klein. (vgl. Wei vs wei)
http://www.studentenwerk-potsdam.de/index.php?id=770

**Comment by ItsNotYou** [comment]
Es fehlen noch die anderen URLs

**Comment by alekiy** [comment]
@ItsNotYou Die anderen fehlen immer noch oder?
