### ISSUE TITLE
RequireJS und JQueryMobile Config

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#483]
see https://github.com/jrburke/requirejs/issues/358
main.js

**Comment by alekiy** [comment]
commits waren für #280 gedacht

**Comment by ItsNotYou** [comment]
Die wrapShim-Option von RequireJS arbeitet uneinheitlich:

- RequireJS ohne Optimizer: Alle Module werden ge-shim-t, egal ob sie explizit (mit define) oder implizit (ohne define) erstellt sind
- RequireJS mit Optimizer 2.2.0: Es werden nur Module mit shim exportiert, die implizit erstellt sind. Bei explizit erstellten Modulen wird das define kopiert, ohne shim-Optionen zu beachten. Letzteres gilt auch für Module, die dynamisch prüfen, ob sie in einer AMD-Umgebung laufen oder nicht.

Das bedeutet, dass wir unsere shim-Anforderungen händisch in Bibliotheken eintragen müssen. Eine bessere Option könnte RequireJS-Preprocessing bieten: http://www.ericfeminella.com/blog/2012/03/24/preprocessing-modules-with-requirejs-optimizer/

**Comment by alekiy** [comment]
Nicht relevant für die neue Version.
