### ISSUE TITLE
Caching in Lageplänen umsetzen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#491]
Lagepläne verwendet derzeit kein Caching. Sinnvolle Einsatzmöglichkeiten wären
- [ ] Laden des Maps-Skriptes
- [ ] Laden der Lageplandaten

**Comment by lkstnr** [comment]
https://github.com/University-of-Potsdam-MM/Mobile.UP/issues/630
