### ISSUE TITLE
App um Screens verkleinern

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#507]
Derzeit sind die Screens und Icons aller Plattformen in der ausgelieferten App enthalten, weil sie im www-Ordner liegen. Wenn diese aus dem www-Ordner entfernt werden, kopiert Cordova nur die wirklich benötigten Dateien und wir sparen Speicherplatz.

**Comment by alekiy** [comment]
see directory structure:
- https://github.com/apache/cordova-plugin-splashscreen
