### ISSUE TITLE
Tester in harten und weichen Kern unterteilen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#519]
Bei

- [x] Google und
- [x] Apple

Gruppen definieren, die separat in Tests einbezogen werden können

**Comment by ItsNotYou** [comment]
@alekiy Wir müssen gemeinsam über die registrierten Tester sehen, da ich nicht alle Namen zuordnen kann

**Comment by ItsNotYou** [comment]
Verfahren für Google Play:
- Wir verwenden geschlossene Alpha- und offene Beta-Tests
- Wir verwalten Tester über Testerlisten

Zugriff für @ckroell und @PhilippJakupovic steht noch aus

**Comment by alekiy** [comment]
Erledigt. Hat etwas gedauert bis die Funktion eingeführt wurde. ;)
