### ISSUE TITLE
Login-Countdown verhindert Tooltip-Lesen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#522]
Wenn der Login-Countdown nach 3x falscher Eingabe permanent die Login-Seite aktualisiert, lässt der Tooltip auf der Seite nicht mehr ausklappen.

**Comment by lkraeh** [comment]
So wäre das Problem gelöst, ist aber vielleicht nicht die eleganteste Lösung. Den Tooltip anzeigen zu lassen, obwohl die Seite jede Sekunde neu lädt, könnte schwierig werden. Soweit ich das verstehe, muss ja wenn dann die ganze Seite neu geladen werden. 
Bin nicht sicher, ob der Tooltip zwingend sichtbar sein muss, wenn der Login drei mal gescheitert ist.
