### ISSUE TITLE
Tipps und Tricks bei Studienberatung erfragen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#527]

**Comment by Clickmari** [comment]
wir dürfen das hier benutzen wohl:
http://www.uni-potsdam.de/studium/konkret/faq/

**Comment by ItsNotYou** [comment]
Die URL existiert nicht mehr. Anscheinend ist jetzt http://www.uni-potsdam.de/studium/konkret/uebersicht.html aktuell

**Comment by alekiy** [comment]
Funktion wird nicht mehr weiter entwickelt.
