### ISSUE TITLE
News-Optionen haben defekten Header

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#528]
Optionsseite zeigt zwei "Zurück"-Pfeile an

**Comment by ItsNotYou** [comment]
Betrifft iPhone  Plus

**Comment by ItsNotYou** [comment]
@Clickmari Kannst du dir das bitte ansehen? Chrome's Device Emulator hat einen iPhone-6-Plus-Modus, in dem werden diese Fehler auch angezeigt. Du kannst also ohne eigenes Gerät daran arbeiten.

**Comment by Clickmari** [comment]
Soll der Pfeil neben dem "fertig" sein oder eher nicht? kann ganz weg oder?

**Comment by ItsNotYou** [comment]
Ganz weg

**Comment by Clickmari** [comment]
erledigt?

**Comment by ItsNotYou** [comment]
Wir brauchen weiterhin die HR-Pfeile. Klasse back-caption wird hinzugefügt

**Comment by ItsNotYou** [comment]
In den Neuigkeiten hüpft das "Logout" nach oben und unten, wenn man in Übersicht vs. Übersichtsoptionen ist.

**Comment by Clickmari** [comment]
Das kleine Springding konnte ich nicht mehr finden...vielleicht hast du dir das eingebildet. aber die schrift ist gerutscht. wie ist es jetz?

**Comment by ItsNotYou** [comment]
von @Kauzig

**Comment by ItsNotYou** [comment]
Letzter Commit musste zurück genommen werden

**Comment by ItsNotYou** [comment]
Scheint gelöst zu sein
