### ISSUE TITLE
Kurs-Ansicht im Vorlesungsverzeichnis ist leer

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#532]

**Comment by ItsNotYou** [comment]
REST- und SOAP-Schnittstelle liefern leere Antwort. @slemcke ist informiert.

**Comment by ItsNotYou** [comment]
Cache für Vorlesungsverzeichnis musste deaktiviert werden. Notwendige Änderungen werden in #561 verfolgt.
