### ISSUE TITLE
Zeit nicht von rotem Balken ablesbar

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#533]
Bsp: AA. Zeitbalken in der Mitte sieht gut aus, aber ohne Zeitwert an den roten Balken dauert es zulange bis man erkennt wie viel Uhr es ist. Vielleicht lieber die Öffnungszeiten präsenter in der Mitte.

von @ckroell

**Comment by alekiy** [comment]
Wird in neuer Version visuell anders implementiert.
