### ISSUE TITLE
Weitere Event-Quellen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#535]
Man könnte noch anderen Läden die Möglichkeit geben ihre Termine dort einzutragen. Z.b. Thalia, Filmmuseum, Landesbibliothek, Hans-Otto-Theater, Olga, La Datscha usw.

von @ckroell

**Comment by alekiy** [comment]
Christian muss die zugehörigen Facebook-Seiten heraussuchen.

**Comment by alekiy** [comment]
@ckroell Bitte die notwendigen IDs heraussuchen.

**Comment by ckroell** [comment]
https://www.facebook.com/thaliapotsdam/

https://www.facebook.com/filmmuseumpotsdam/

https://www.facebook.com/Hans-Otto-Theater-160875547269982/

https://www.facebook.com/museumbarberini/

https://www.facebook.com/museumFLUXUSplus/

https://www.facebook.com/kunstraumpotsdam/

https://www.facebook.com/fabrikpotsdam/

https://www.facebook.com/HBPG.im.Kutschstall/

https://www.facebook.com/PotsdamerKabarettObelisk/

https://www.facebook.com/awokulturhaus.babelsberg/

https://www.facebook.com/Nikolaisaal.Potsdam/

https://www.facebook.com/theater.poetenpack/

https://www.facebook.com/theaterschiffpotsdam/

**Comment by alekiy** [comment]
Wollen wir alle aufnehmen?

**Comment by ckroell** [comment]
Würde sagen ja. In den Einstellungen kann man ja die Eventquellen abwählen die einen nicht interessieren.

**Comment by ckroell** [comment]
Moin,
ich würde sagen ja. In den Einstellungen kann man ja die Eventquellen 
abwählen die einen nicht interessieren.
Beste Grüße
Christian

**Comment by ckroell** [comment]
Thalia: 96031304080
Filmmuseum: 152680081417473
Hans-Otto-Theater: 160875547269982
Barberini: 1068121123268077
MuseumFluxus: 184666797941
Kunstraumpotsdam: 210087225671713
Fabrik Potsdam: 254848751194733
Haus der Brandenburgisch-Preußischen Geschichte: 247015508644929
Kabarett Obelisk: 211335195560137
AWO Kulturhaus Potsdam: 474281182710249
Nikolaisaal Potsdam: 144526598919086
Theater Poetenpack: 304544522939016
Theaterschiff Potsdam: 969193153100182

**Comment by lkstnr** [comment]
https://github.com/University-of-Potsdam-MM/Mobile.UP/issues/631
