### ISSUE TITLE
Keine Umlautunterstützung

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#540]
![img_0029](https://cloud.githubusercontent.com/assets/1041388/21390552/be0d3df6-c787-11e6-9818-c93d91f917e2.PNG)

von @PhilippJakupovic 

Der Server mag das Sonderzeichen "ä" nicht

@alekiy sagt: "Der Service wird von PHP auf Java umgestellt, das wird jedoch noch etwas dauern und passiert im Rahmen meines Projekts."

**Comment by ItsNotYou** [comment]
Bitte testen in 40008 / 201612231454.

**Comment by alekiy** [comment]
Funktioniert in der neuen Version mit dem neuen Provider nun ohne Probleme.
