### ISSUE TITLE
Back Button führt ins Hauptmenü

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#553]
Raumbelegung>Freie Räume>Haus 1>(Raum) 2.48.>Keine Reservierungen. Schaut man sich in der Raumbelegung Informationen für einen bestimmten Raum an und drückt dann den Back Button des Handys (nicht den in der APP) landet man direkt wieder im Hauptmenü. Auf den Geräten S3, S6 und Nexus.

von @ckroell

**Comment by ItsNotYou** [comment]
@ckroell bitte einmal mit Version 40100 testen

**Comment by alekiy** [comment]
Getestet auf Nexus mit Hardware-Tasten. Funktioniert.
