### ISSUE TITLE
See more of it

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#558]
In der alten Appversion (Nexus und SIII) und in der neuen Appversion (S6) funktioniert nirgendwo die Weiterleitung (?) "See more of it".

von @ckroell 

Das "see more of it" ist von geringer Priorität, da der Link darunter funktioniert. Der Link wird vom Server entfernt, es muss also dort angesetzt werden

**Comment by alekiy** [comment]
Parser muss angepasst werden.

**Comment by alekiy** [comment]
```sql
UPDATE mobileup_prod.news SET text = REPLACE(text, 'see more of it', '');
UPDATE mobileup_prod.news SET description= REPLACE(description, 'see more of it', '');
```
https://gitup.uni-potsdam.de/elis/potsdamevents/commit/43307988f0fc0f695affaa03023d061905a1195b
