### ISSUE TITLE
Umstellen auf MVC-Struktur

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#561]
Mit der MVC-Struktur können wir uns die bisherige Struktur des Vorlesungsverzeichnisses sparen und stattdessen jeden Knoten in einer eigenen Seite darstellen. Damit könnte auch der Cache wieder aktiviert werden.

**Comment by ItsNotYou** [comment]
@PhilippJakupovic @ckroell kann bitte einer von euch 40101 / 201703081607 testen

**Comment by ckroell** [comment]
Auf dem iPad Mini 2 und dem iPhone 6s getestet. Keine Fehler gefunden.
