### ISSUE TITLE
Home-Screen auf iOS bei Initialstart nach oben verschoben

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#563]
Hallo Mobile-UP Dev-Team,

soeben wurde die Mobile.UP Version 4.0.1 vom 12.01.2017 auf iOS veröffentlicht. Ich habe einen kleinen GUI Bug gefunden. 

Wenn die App gestartet ist, wird der Text "Mein Studium" abgeschnitten. Siehe Bildschirmfoto. Auch wenn man einmal nach unten scrollt und dann wieder nach oben flippt, bleibt die Ansicht die selbe.

iOS 10.2 iPhone 6s

![image](https://cloud.githubusercontent.com/assets/2682987/21978170/a9e43c38-dbd9-11e6-82da-9599efe91a5c.png)

**Comment by ItsNotYou** [comment]
Scheint gelöst zu sein.
