### ISSUE TITLE
Uni- und Hochschulsport-Events werden nicht angezeigt

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#564]
Die Uni sammelt ihre Veranstaltungen (inkl. Hochschulsport) auf http://www.uni-potsdam.de/uniges/nachrichten-veranstaltungen/veranstaltungen.html

Facebook bleibt dagegen weitestgehend leer.

**Comment by alekiy** [comment]
@ItsNotYou Kein Handlungszwang oder sehe ich das falsch?

**Comment by ItsNotYou** [comment]
Kein Zwang, führt aber dazu, dass wir uns die Uni-Events in der aktuellen Form sparen können

**Comment by alekiy** [comment]
Es gibt also keine dedizierte Quelle mehr für Hochschulsport Events, sondern werden über die Nachrichten / Veranstaltungen von uni-potsdam.de gepflegt richtig?

**Comment by lkstnr** [comment]
https://github.com/University-of-Potsdam-MM/Mobile.UP/issues/631
