### ISSUE TITLE
Hauptmenü überarbeiten

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#567]
Das Hauptmenü soll sortierbar und favoritisierbar gemacht werden.

![index](https://cloud.githubusercontent.com/assets/1041388/22828698/0e594392-ef9f-11e6-985a-3eea1b8208c7.png)
![index-menu](https://cloud.githubusercontent.com/assets/1041388/22828699/0f7d252c-ef9f-11e6-9dc6-8f587603fe46.png)

- [ ] Alle Funktionen werden als gruppierte Liste präsentiert
- [ ] Eine durch den Nutzenden sortierbare Anzahl an Kacheln sind Favoriten

**Comment by Clickmari** [comment]
Hendrik hat einen prototyp gebaut, dazu muss aber jquery/jquery mobile und jquery ui funktionieren, tut es aber nicht. Alles, was man dafür braucht liegt im Ordner jquery. U.A. eine aktuelle jquery / jquery mobile version, die könnte ohnehin mal aktualisiert werden, trau ich mich aber nicht.

Du klickst in Hendriks Version Menu > Stundenplan >Stundenplan > Gear > Optionen >Stundenplan (> optional Stundenplan), da kann man dann die Kacheln verschieben

da es nicht funktioniert, gibt es oben in der kopfzeile auch kein menu. da müsste rein: auf der Startseite: Schnelleinstieg bearbeiten (schaltet dann die Funktion zum verschieben der Kacheln ein), ggf. logout und bei news und events noch "Optionen" o.ä.. Dieser logout-button und das Zahnrädchen können weg.


[jqmspike.zip](https://github.com/University-of-Potsdam-MM/Mobile.UP/files/1348584/jqmspike.zip)

**Comment by alekiy** [comment]
Ist in der neuen Version integriert.
