### ISSUE TITLE
Mensaübersicht leer in Chrome Browser bei M & P

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#568]
Urgent!

**Comment by ItsNotYou** [comment]
Zwei Schritte fallen mir dazu ein
1. Wir verwenden die minifizierte JS-Variante, um Fehlerquellen zu reduzieren
2. Wir setzen das Caching im Apache intelligenter ein http://metaskills.net/2006/02/19/how-to-control-browser-caching-with-apache-2/

**Comment by ItsNotYou** [comment]
Caching ist auf einen Tag gesetzt

**Comment by ItsNotYou** [comment]
Bei P. prüfen

**Comment by ItsNotYou** [comment]
Gelöst
