### ISSUE TITLE
Mehr Kursinformationen im Vorlesungsverzeichnis anzeigen

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#571]
Im Moment werden nur Gruppeninformationen angezeigt.
Es gibt jedoch noch ein Kommentarfeld oder Beschreibungstext.
Dieser sollte entsprechend angezeigt werden.
- [x] Template erweitern und Inhalte darstellen

**Comment by alekiy** [comment]
@Clickmari Schau mal im Commit-Kommentar. Dann wieder zurück.

**Comment by Clickmari** [comment]
geschaut. und nun? ich versteh nichts... was is ne gruppeninformation? 
Wenn ich nen Kurs aufklappe, denn steht da nix.

**Comment by alekiy** [comment]
Ah im Template ist aktuell ein console.log(empty) dafür einen Hinweis einfügen, dass bisher keine Kursinformationen zur Verfügung stehen.

**Comment by Clickmari** [comment]
Dit heißt, ich soll da jetz reinschreiben "<p> Es gibt bisher keine Informationen zu diesem Kurs </p>" ? ... ?

**Comment by alekiy** [comment]
Schau mal. Die Anzeige etwas formatieren, z. B. dass die Texte links oben hängen und nicht zentriert ggf. mit Border bot zur visuellen Unterteilung.
Das Template ist lectures/lectures_course.tmpl

![screenshot](https://user-images.githubusercontent.com/2682987/31533460-a1b7465c-aff2-11e7-8581-96ee1f914f93.png)

**Comment by alekiy** [comment]
Damit du dich nicht durcklicken musst hier die URL zum anfügen:
/#lectures/lectures/140126/false/Grundlagen%20der%20Programmierung

**Comment by alekiy** [comment]
@Clickmari Status? ;) Hattest du noch ein wenig formatiert?

**Comment by Clickmari** [comment]
nee, ich schrieb dir, dass ich keinen kurs mit so infos drinn finden kann, dieser war weg.

**Comment by alekiy** [comment]
Suchst dir halt einen neuen Kurs. ;D

**Comment by alekiy** [comment]
Ist in der neuen Version erledigt.
