### ISSUE TITLE
Lizenzen von Frameworks abklären und innerhalb der App auflisten

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#574]
- siehe StApps Projekt

**Comment by ItsNotYou** [comment]
@alekiy im StApps Projekt habe ich keine Lizenzauflistung gesehen. Eine Wiki-Seite ist unter https://github.com/University-of-Potsdam-MM/Mobile.UP/wiki/Frameworks#lizenzen eingerichtet

**Comment by ItsNotYou** [comment]
Ich hoffe ich habe jetzt alles erwischt. Jemand müsste noch klären, was wir wo anzeigen müssen. @alekiy falls Philipp nicht der richtige dafür ist bitte korrigieren

**Comment by alekiy** [comment]
https://www.stapps.tu-berlin.de/#/b-tu/about/librariesAndLicences

**Comment by alekiy** [comment]
Muss von einem in die vorbereitete Form übertragen werden.

**Comment by alekiy** [comment]
Schaffst du ein Accordion in einem Accordion? damit die drei Rubriken erst einmal minimiert sind. Alternativ einfach leichte Trennlinien (gepunktet o.ä.) zwischen den Zeilen.

**Comment by Clickmari** [comment]
klar schaff ich. aber das liest ohnehin niemand...
