### ISSUE TITLE
Anzeige der Zusatzstoffe

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/Mobile.UP#585]
Zusatzstoffe werden jetzt am unteren Rand des Angebotes angezeigt. Bei Klick auf einen Zusatzstoff öffnet sich die Erklärungsübersicht des Studentenwerkes. @Clickmari kannst du bitte überprüfen, ob da noch etwas verändert oder anders gestyled werden muss?

![2017-08-09 13 47 57](https://user-images.githubusercontent.com/1041388/29125315-c3eb1ef6-7d1b-11e7-9171-e1331800d123.png)

![2017-08-09 13 48 05](https://user-images.githubusercontent.com/1041388/29125322-c5b9dfd8-7d1b-11e7-9390-323e741b77de.png)

**Comment by alekiy** [comment]
Sollte erst einmal passen.
