### ISSUE TITLE
Kachel für Reflect.UP hinzufügen

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#588]
- Bitte eine Kachel für die Reflect.UP und den Home-Screen gestaltet. Das bekannte Logo übernehmen, nur die Farben anpassen:
https://github.com/University-of-Potsdam-MM/Reflect.UP/blob/master/res/icon/android/icon-72-hdpi.png

**Comment by Clickmari** [comment]
Farben anpassen? Welche Farbe willste denn?

**Comment by alekiy** [comment]
Na so dass es zu den aktuellen Kacheln passt. ;) Irgendwas mit Blau und hellem Blau.

**Comment by Clickmari** [comment]
in pmodules/home/home.tpl müssten dann ab Zeile 36 ggf. die Pfade angepasst werden.

**Comment by alekiy** [comment]
- [ ] Intent / Launch für Reflect.UP einbauen @ItsNotYou Willst du dich probieren?

**Comment by alekiy** [comment]
- [ ] Web-Endpoint für Reflect.UP einrichten

**Comment by alekiy** [comment]
launching in same webview has to be fixed

**Comment by alekiy** [comment]
https://github.com/EddyVerbruggen/Custom-URL-scheme

**Comment by alekiy** [comment]
https://github.com/nchutchind/cordova-plugin-app-launcher
