### ISSUE TITLE
Mobile UP - Vorlesungsverzeichnis

### ISSUE THREAD

**Issue by PhilippJakupovic** [University-of-Potsdam-MM/Mobile.UP#590]
Wenn "kein Element verfügbar" angegeben wird, ist es irrelevant dafür überhaupt einen Schritt weiter gehen zu können.

<img width="1294" alt="screen shot 2017-10-10 at 15 27 19" src="https://user-images.githubusercontent.com/24587687/31389277-d0a3853a-add0-11e7-9532-cf4aba467227.png">

**Comment by PhilippJakupovic** [comment]
gilt für iOS und windows

**Comment by alekiy** [comment]
Wurde in der neuen Version anders implementiert.
