### ISSUE TITLE
Zeit hinter dem Datum ist in der Überschrift 00:00

### ISSUE THREAD

**Issue by PhilippJakupovic** [University-of-Potsdam-MM/Mobile.UP#591]
<img width="1293" alt="screen shot 2017-10-10 at 15 25 41" src="https://user-images.githubusercontent.com/24587687/31389328-fd941d98-add0-11e7-9be2-2e0335873072.png">

**Comment by PhilippJakupovic** [comment]
gilt für iOS und windows

**Comment by lkraeh** [comment]
Der aktuelle Tag wird in `calendar.js:53` mit 
```js 
if (!this.day || !this.day.isValid()){
    this.day = moment();
}
```
geholt. Bereits hier hat die Uhrzeit den Wert `00:00`. An `moment.js` sollte es aber eigentlich nicht liegen können.

**Comment by lkraeh** [comment]
Es wäre vielleicht auch eine Option, die Uhrzeit hier einfach ganz wegzulassen, da sie sowieso nicht relevant ist. Die Zeit auf dem Smartphone schließlich permanent in der Statusleiste zu sehen.

**Comment by alekiy** [comment]
Gute Idee und hast wahrscheinlich auch recht. Wir lassen es erst einmal drin. Danke für den Hinweis.
