### ISSUE TITLE
Kommas bei Neuigkeiten nicht schön

### ISSUE THREAD

**Issue by PhilippJakupovic** [University-of-Potsdam-MM/Mobile.UP#592]
<img width="165" alt="screen shot 2017-10-10 at 15 38 49" src="https://user-images.githubusercontent.com/24587687/31389371-23bc0116-add1-11e7-9b39-6d17c0dfb79a.png">

**Comment by alekiy** [comment]
Anpassung im Webservice notwendig

**Comment by PhilippJakupovic** [comment]
gilt für iOS und windows

**Comment by alekiy** [comment]
In neuer Version anders implementiert.
