### ISSUE TITLE
Logout Symbol nach oben rechts

### ISSUE THREAD

**Issue by PhilippJakupovic** [University-of-Potsdam-MM/Mobile.UP#593]
<img width="228" alt="screen shot 2017-10-10 at 15 27 26" src="https://user-images.githubusercontent.com/24587687/31389399-451bc79c-add1-11e7-8517-867844b743b5.png">

**Comment by PhilippJakupovic** [comment]
gilt für iOS und windows

**Comment by alekiy** [comment]
Obsolet für neue Version
