### ISSUE TITLE
PList Anpassungen prüfen

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#597]
- hook
- variable name
vgl. https://stackoverflow.com/questions/22769111/add-entry-to-ios-plist-file-via-cordova-config-xml

**Comment by ItsNotYou** [comment]
Hook existiert unter https://github.com/University-of-Potsdam-MM/Mobile.UP/commit/a0bc512264d0a96f94c83b79d7edc67d49cb22e2#diff-bda3b0ebae9cbc03c4c1089bd5109937

Die Plugin-Variante sieht besser wartbar aus.

**Comment by ItsNotYou** [comment]
Seit Cordova 6.x existiert [edit-config](https://cordova.apache.org/docs/en/6.x/plugin_ref/spec.html#edit-config), das sollte unser präferierter Weg sein.

```
<edit-config target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
    <string>need location access to find things nearby</string>
</edit-config>
```

**Comment by alekiy** [comment]
see #624
