### ISSUE TITLE
Kalender Export scheint seit letztem Update nicht mehr zu funktionieren

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#606]

**Comment by alekiy** [comment]
![screenshot_2017-10-31-23-57-24-597_de floriangoessler upapp](https://user-images.githubusercontent.com/2682987/33597364-869cf8d6-d99f-11e7-8350-3321c8895949.png)
![screenshot_2017-10-31-23-57-30-535_de floriangoessler upapp](https://user-images.githubusercontent.com/2682987/33597368-88f9d4be-d99f-11e7-8eb3-707874622582.png)
![screenshot_2017-10-31-23-57-47-871_de floriangoessler upapp](https://user-images.githubusercontent.com/2682987/33597378-8dd5bafc-d99f-11e7-8a8f-f5c5474eecbe.png)

**Comment by lkraeh** [comment]
Es liegt offenbar (u.a.) daran, dass manche Kurse kein Attribut `timespan` haben. In `calendar.common.js:54` in `exportToCalendar()` wird jedoch versucht, dieses Attribut zu holen und `.split()` darauf auszuführen. Das führt zu einem Fehler, da `timespan` eben nicht definiert ist.

```js
exportToCalendar: function(entry, course, callback) {
			var split = this.get("timespan").split(' ');
			var dayContent = moment(split[1], "DD.MM.YYYY");

			entry.startDate = this.getBegin(dayContent).toDate();
			entry.endDate = this.getEnd(dayContent).toDate();

			callback(entry);
		}
```

**Comment by lkraeh** [comment]
Eine kleine Umgestaltung schafft Abhilfe, das heißt, es liegt tatsächlich daran. 
```js
exportToCalendar: function(entry, course, callback) {
			if (this.get("timespan")){
				var split = this.get("timespan").split(' ');
			} else {
				var dayContent = moment().format("DD.MM.YYYY")
				// var split = this.get("timespan").split(' ');
				// var dayContent = moment(split[1], "DD.MM.YYYY");
			}
			
			entry.startDate = this.getBegin(dayContent).toDate();
			entry.endDate = this.getEnd(dayContent).toDate();

			callback(entry);
		}
```

**Comment by lkraeh** [comment]
Scheint bei manchen Benutzern doch noch ein Problem zu sein. Ich denke, das liegt an bestimmten Kombinationen aus Veranstaltungsrhythmus eines Kurses und dem, was tatsächlich in PULS steht. Das System gibt Dozenten ja teils verschiedene Möglichkeiten, die Veranstaltungszeiträume einzutragen. Manche davon bereiten wohl Probleme und führen irgendwo im Export zu einem Fehler, weil diese konkrete Kombination durch den Code nicht abgedeckt wird.
Allerdings ist schwer testbar, woran es dann in jedem einzelnen Fall liegt. Man bräuchte zum einen eine Liste der Kurse, die Studenten, bei denen das Problem auftritt, belegt haben und zum anderen die Möglichkeit, sich mal eben in diverse Kurse einzuschreiben. 

Ich weiß im Moment jedenfalls von zwei Studenten, bei denen es nicht funktioniert. Einer davon braucht es aber nicht wirklich und der andere hat die Kurse mittlerweile manuell in seinen Kalender übertragen.

**Comment by alekiy** [comment]
@lkraeh Kontakt aufnehmen und bitte einen Tag nach Gbsee zu kommen, so dass du es testen kannst oder dir die Kurse besorgst.
