### ISSUE TITLE
Vorschläge/Gemeldete Problem bezüglich des Mensaplans

### ISSUE THREAD

**Issue by ckroell** [University-of-Potsdam-MM/Mobile.UP#622]
Vorschläge/Gemeldete Problem bezüglich des Mensaplans am Tag der Internationalisierung

a) Mensaplan aktualisieren wenn es ein Gericht nicht mehr gibt
b) Der Mensaplan stimmte nicht
c) Mensaplan für "Ulf" stimmt nicht

**Comment by alekiy** [comment]
Sollte sich erledigt haben. Wir sind maßgeblich auf die Datenpflege seitens des Studentenwerks angewiesen...
