### ISSUE TITLE
Geringste Version für Release klären (iOS 9?)

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#627]

**Comment by lkstnr** [comment]
Geringste Version ist iOS 11+ / Android 4.4+, wegen dem Ionic Webview Plugin:
https://github.com/ionic-team/cordova-plugin-ionic-webview

Derzeit sind 92% aller iOS-Geräte iOS 11+:
https://developer.apple.com/support/app-store/

Und 96.5% aller Android-Geräte 4.4+: 
https://developer.android.com/about/dashboards/
