### ISSUE TITLE
Lageplan-Verbesserungen

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#630]
- [x] Suche hinzufügen
- [x] Horizontal <-> Landscape (teilweise graue Ränder, ggf. Karte neuladen?)
- [x] Caching
- [ ] Gebäude mit Räumen annotieren (?)
- [ ] Ähnliche Orte (?)
- [ ] Aktualität der Informationen exemplarisch prüfen
- [x] Position des Nutzer anzeigen
- [ ] Fuß-Routen (?)
- [x] Übersetzung ins Englische

**Comment by weihmann** [comment]
Was das Anzeigen des Standortes betrifft: Soll die Karte nach Aktivieren der Ortung immer zum aktuellen Standort springen, unabhängig davon, ob man überhaupt an einem der Campus ist? Aktuell passiert das nicht.

**Comment by alekiy** [comment]
Nein. Standort anzeigen aber nicht dort hin springen.

**Comment by weihmann** [comment]
Okay, dann passt das ja so.

**Comment by weihmann** [comment]
@alekiy Könntest du bitte bei Gelegenheit für die Universität einen API-Key für [Open-Route-Service](https://openrouteservice.org/dev/#/login) erstellen? Würde das gerne für die Navigation über den Campus verwenden.

**Comment by weihmann** [comment]
- [ ] Verwenden von ngx-leaflet (würde das ganze wahrscheinlich einfacher machen)
- [ ] Verwenden einer angular component in den leaflet popups. Wäre die Vorbedingung, um dynamische Inhalte für Gebäude zu zeigen.

**Comment by alekiy** [comment]
@weihmann Sollen wir für das nächste Release noch auf die Funktionen warten oder bearbeiten wir die weiteren Punkte im nächsten Meilenstein.

**Comment by weihmann** [comment]
Bis zum Ende des aktuellen Meilensteins, also Ende März, habe ich die übrigen Punkte sicherlich. Falls vorher schon released werden soll, bin ich mir nicht ganz sicher.

**Comment by weihmann** [comment]
@lkstnr Könntest du dir bitte bei Gelegenheit mal ansehen, wieso sich das Modal, das geöffnet wird, wenn man ein Gebäude klickt, nicht mehr über den Button oben links schließen lässt? Ich komme nicht drauf, was da nicht passt.

Der Fehler liegt vermutlich [hier](https://github.com/University-of-Potsdam-MM/Mobile.UP/blob/0a740629cb3b071cf343ef9cf197ea74a258a803/src/app/components/campus-map-feature-modal/campus-map-feature-modal.component.ts#L19) oder [hier](https://github.com/University-of-Potsdam-MM/Mobile.UP/blob/0a740629cb3b071cf343ef9cf197ea74a258a803/src/app/pages/campus-map/campus-map.page.ts#L347).

Danke :)

**Comment by lkstnr** [comment]
Fixed! Hab das `modalCtrl.create` ins `geoJson.on('click')` verschoben.

Dinge, die beim kurzen Ausprobieren noch aufgefallen sind: 
a) Wenn über die Suche ein Haus auf einem anderen Campus ausgewählt wurde, sollte das oben im Campus-Tab wahrscheinlich auch geändert werden, damit der Nutzer das irgendwie mitbekommt, dass sich der Campus geändert hat.

b) Nach Auswahl eines Hauses in der Suchleiste sind danach HTML-Tags in der Suchleiste zu sehen (Bspw. `Haus 4: <br/> Institut für Informatik`)

**Comment by weihmann** [comment]
Danke!

**Comment by weihmann** [comment]
Was a) angeht: Ich denke, das sollte mit einer Änderung des CampusTab Menüs einhergehen, da sich der aktuelle Campus nicht ohne weiteres ändern lässt, ohne, dass das change-Event emittiert wird. Das wiederum führt dazu, dass die Karte automatisch neu-ausgerichtet wird, was ja nicht sein muss, wenn der Benutzer eh schon am anderen Campus ist.
Außerdem wäre es dann, wie schonmal von Alex erwähnt wurde, sinnvoll, das `ICampus` interface zu verwenden, das würde auch einiges erleichtern.

**Comment by weihmann** [comment]
Bleibt nur ein kleiner Bug: Das Ebenen-Umschalten funktioniert zwar, aber aus irgendeinem Grund erst, wenn man eine Ebene an-, ab- und wieder anschaltet.
Scheint mehr oder weniger bekannt zu sein, die Vorschläge hier helfen aber alle nicht.

https://github.com/Asymmetrik/ngx-leaflet/issues/182
https://github.com/Asymmetrik/ngx-leaflet/issues/108
https://github.com/Asymmetrik/ngx-leaflet/issues/193

**Comment by weihmann** [comment]
Ich schließe dieses Ticket mal. Die wichtigsten Punkte sind erstmal erledigt. Die verbleibenden Punkte bearbeite ich in anderen Tickets.
