### ISSUE TITLE
Events: Möglichkeiten prüfen

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#631]
- [ ] Uni und Hochschulsport-Events https://github.com/University-of-Potsdam-MM/Mobile.UP/issues/564
- [ ] Event-Quellen überprüfen + Filter https://github.com/University-of-Potsdam-MM/Mobile.UP/issues/535

**Comment by alekiy** [comment]
Probleme mit Facebook bestehen in der Überarbeitung der Graph API:

- https://developers.facebook.com/tools/explorer/?method=GET&path=118227928234829%2Fevents%3Ffields%3Did%252Cname%252Cdescription%252Cticket_uri%252Cstart_time%252Cend_time%252Cupdated_time%252Cplace&version=v2.7

- https://developers.facebook.com/tools/explorer/?method=GET&path=118227928234829%2Ffeed&version=v3.0#

- https://developers.facebook.com/tools/debug/accesstoken/?access_token=1454520007987990%7C36a957a35f6216b1cbf477e1eabf924f
