### ISSUE TITLE
Caching-Optionen in Config auslagern

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#634]
- [x] Caching-Paramter in Config auslagern
- [x] Page-Template mit allgemeinen Funktionen (Pull to Refresh; Connection Check etc.) erstellen und für Seiten nutzen

**Comment by weihmann** [comment]
Punkt 1 bearbeite ich zufälligerweise gerade in #636. Ich kann in dem WebserviceWrapper, den ich gerade erstelle, das Caching für jeden http request, der mit diesem Wrapper ausgeführt wird, steuern.  Die Standard Caching Parameter für jeden Request lagere ich dann noch in die Config aus.

**Comment by lkstnr** [comment]
Das Ticket ist damit ja dann eigentlich durch. Die abstrakte Seite nutzen wir ja auch schon.
