### ISSUE TITLE
Drag & Drop für Kacheln auf HomeScreen

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#635]

**Comment by alekiy** [comment]
- Bibliothek recherchieren für Umsetzung

**Comment by weihmann** [comment]
- https://github.com/tiberiuzuld/angular-gridster2  sieht brauchbar aus:
- https://material.angular.io/cdk/drag-drop/overview sieht sogar besser aus, funktioniet aber u.U. nicht mit Ionic

**Comment by weihmann** [comment]
angular-gridster2 wirkt vernünftig, werde es damit versuchen.

**Comment by weihmann** [comment]
Ist jetzt schon ganz brauchbar. Kacheln werden hinzugefügt, wenn man ein Modul favorisiert. Nach dem Verändern des grids wird das veränderte grid gesichert. Verschieben klappt auch auf em Smartphone gut. Noch zu tun:

- [ ] Styling der Kacheln
- [ ] Vertikalen Platz des grids reduzieren, will aktuell immer 100% haben
- [ ] nice to have: Kachel löschen durch ziehen auf "Mülleimer"-Feld
