### ISSUE TITLE
HTTP Requests in Provider kapseln

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#636]
#634

**Comment by weihmann** [comment]
Würde dafür den `WebServiceProvider` vorschlagen, der jetzt existiert.

**Comment by weihmann** [comment]
Ich würde den [Service](https://github.com/University-of-Potsdam-MM/Mobile.UP/blob/636-http-calls-wrapper/src/app/services/webservice-wrapper/webservice-wrapper.service.ts) jetzt als einigermaßen fertig bezeichnen. Was der Service kann:
- man kann in wenigen Zeilen einen Webservice definieren ohne sich oft zu wiederholen (so wie es bisher der Fall war). Dazu habe ich ein paar `default header` und `default responseCallbacks` angelegt
- man kann Funktionen für `response` und `error callbacks` angeben, die dann, sofern definiert, verwendet werden um die Antwort oder einen Fehler zu verarbeiten. Im Moment ist die `responseCallback` bei allen die selbe (default), bis auf ein paar der PULS webservices, da wird 'no user rights' schon behandelt. Das `errorCallback` ist erstmal bei allen gleich, was eigentlich auch nicht schlecht ist.
- man kann das Caching-Verhalten bei einem Aufruf des Services selbst steuern oder gleich in der `config.json` default Werte anlegen (hab ich auch an ein paar Stellen gemacht)

Was ich nicht _ganz_ ideal finde, ist, dass man für die Parameter, die die `buildRequest` Funktionen brauchen, kein Typing hat, aber dafür ist mir jetzt außer optionalen Interfaces für die Parameter keine Lösung eingefallen, die nicht wieder alles komplizierter macht.

@alekiy @lkstnr Könntet Ihr euch das bei Gelegenheit mal anschauen und etwas Feedback geben? 

Ich sehe auch, dass an ein paar Stellen cache-Items manuell bei einem Refresh gelöscht werden ([Beispiel](https://github.com/University-of-Potsdam-MM/Mobile.UP/blob/607abc5ab723518fcd357b68c52b6d52a0ec8053/src/app/pages/library-search/library-search.page.ts#L311)). Ist das wirklich nötig? Ich wäre jetzt davon ausgegangen, dass der cache Service das sowieso überschreibt, wenn ein neues Cache-Item mit dem selben key angelegt wird. Oder verstehe ich das falsch?

**Comment by lkstnr** [comment]
Ohne es jetzt ausprobiert zu haben, sieht das für mich gut und nachvollziehbar aus. 

Zum manuellen Refresh: wenn man die Items nicht entfernt und die TTL noch nicht abgelaufen ist, gibt der Cache Service soweit ich weiß immer den cached Request zurück. Das heißt es gäbe keinen Weg die Aktualisierung der Daten zu erzwingen (wenn man z.B. auf die Eintragung einer Note wartet).

**Comment by weihmann** [comment]
Okay, danke!

Ach ja, klar. Ist ja schließlich ein Cache, das hab ich irgendwie falsch verstanden. Werde dann die Möglichkeit eines force-refresh in den Service einbauen. Dann muss man in den Pages garnicht mehr direkt mit dem Cache hantieren.
