### ISSUE TITLE
Build-Automatisierung einrichten

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#647]
- https://github.com/rakatyal/cordova-docs-1/blob/master/tutorial-team-build/Jenkins.md

Der Build ist vorerst hier erhätlich:

https://elis.soft.cs.uni-potsdam.de/mobileup/platforms/browser/www/

Die URL wird noch umgestellt sobald alles funktioniert.
Problem see: - https://issues.apache.org/jira/browse/CB-11419

**Comment by alekiy** [comment]
Build ohne `--prod`-Flag
- https://github.com/typeorm/ionic-example/issues/23

**Comment by alekiy** [comment]
- https://forum.ionicframework.com/t/pwa-localhost-8000-screen-404-not-found-and-google-analytics-proxy-error/82011/3

**Comment by alekiy** [comment]
@lkstnr Wie hast du nochmal den Back-Button resp. das Tab-Menu ausgeblendet wenn man per URL direkt auf eine Seite geht?

**Comment by lkstnr** [comment]
Der Back-Button wird automatisch ausgeblendet, wenn es keine vorherige Seite im Stack gibt. Und das Tab-Menu war noch ein offenes Problem, bevor wir es entfernt haben.

**Comment by alekiy** [comment]
Ist das mit dem Stack ein Standardverhalten oder finde ich die Zeile in `app.components.ts`? ;) Muss ja nun das Seitenmenu ausblenden ;D

**Comment by alekiy** [comment]
Mobile Versio verfügbar unter: https://mobileup.uni-potsdam.de/

**Comment by lkstnr** [comment]
Ist ein Standardverhalten beim Back-Button. Weiß nicht, ob es da ne schlaue Lösung fürs Seitenmenü gibt.

**Comment by alekiy** [comment]
Build ist eingerichtet: https://makeup.cs.uni-potsdam.de/job/Apps/job/MobileUP/
