### ISSUE TITLE
Export des Konsolen-Outputs für Support-Anfragen

### ISSUE THREAD

**Issue by weihmann** [University-of-Potsdam-MM/Mobile.UP#653]
Wäre vielleicht eine Idee, einen Logger zu verwenden, der es erlaubt, den Log zu exportieren. Diesen Log könnte dann ein Benutzer bei einer Support-Anfrage anhängen. Ausgabe der Datei zum Beispiel bei der InfoPage über einen "Log export" Button.

[Dieser Service](https://www.npmjs.com/package/ionic-logging-service) würde das einfach machen. Man müsste dann halt an wichtigen Stellen der App und bei Fehlern diesen logger aufrufen.

**Comment by alekiy** [comment]
- https://robferguson.org/blog/2017/09/09/a-simple-logging-service-for-angular-4/

**Comment by lkstnr** [comment]
Find ich super. Wäre vielleicht sinnvoll, dass auch als Submodule auszulagern (vgl. LoginService / LoginProvider), damit es auch für Reflect.UP nutzbar ist.

@weihmann Hast du damit schon begonnen? Sonst könnte ich das auch ggf. übernehmen.

**Comment by weihmann** [comment]
Hab mehrmals angefangen und wurde nicht glücklich damit. Ich wollte das so machen, dass man diesen Service dann direkt auf der abstrakten Seite instanziert, damit jede Seite gleich ihren eigenen Logger hat, der auch schon weiß, wie die jeweilige Seite heißt.
Hab aber keine gute Möglichkeit gefunden, den Log dann wieder zu exportieren oder überhaupt lokal zu speichern. Kannst du gerne versuchen, vielleicht hast du mehr Erfolg.

**Comment by lkstnr** [comment]
https://github.com/University-of-Potsdam-MM/Mobile.UP/tree/653-console-logger

Ich hab das jetzt grundsätzlich zum Laufen bekommen. Überall, wo vorher `console.log` verwendet wurde, kommt jetzt der Logger zum Einsatz (`logger.debug` oder `logger.error`). Der speichert es lokal und gibt es auch in der Browser-Konsole aus. 

Man müsste noch schauen, ob weitere Stellen geloggt werden sollten. Die Http-Requests waren dank des Services immerhin einfach log-bar.

Export-Button ist jetzt (vorläufig?) im Seitenmenü und gibt einem dann die Möglichkeit, die `log.txt` per E-Mail zu verschicken. Vielleicht könnte man noch eine Option hinzufügen, den Log ohne Email zu übermitteln, falls manche auf ihren Handys keinen Email Account eingerichtet haben.

**Comment by weihmann** [comment]
Sieht sehr gut aus! Ich wollte es auch erst mit dem selben Plugin versuchen, aber irgendwie hatte es bei mir immer den Ursprung (Datei und Zeile) des Log-Calls verworfen. 
Auch der Export gefällt mir. Ich sehe nur, dass da teilweise ziemlich viele (überflüssige) Daten in den einzelnen Einträgen stehen können, aber das muss man dann ja nur entsprechend anpassen, andererseits könnten gerade diese Server-Antworten auch für das Debugging relevant sein. Und persönliche Daten oder Passwörter werden ja, denke ich, eh nirgends geloggt, also sollte das auch kein Problem sein.

Den Export-Button würde ich vielleicht eher im `Info` Bereich unterbringen. Die Funktion wird (die meisten) Nutzer entweder nicht interessieren oder irritieren.
