### ISSUE TITLE
ConfigProvider vs storage.get("config")

### ISSUE THREAD

**Issue by weihmann** [University-of-Potsdam-MM/Mobile.UP#663]
Aktuell wird ja beides in der App verwendet. Sowohl der `ConfigProvider`, den ich mal eingeführt hab (habe ich von [hier](https://blogs.msdn.microsoft.com/premier_developer/2018/03/01/angular-how-to-editable-config-files/)), als auch die Config einfach async vom `storage` zu holen. Bin mir nicht ganz sicher, was nun die bessere Methode ist.   
Für den `ConfigProvider` spricht meiner Meinung nach auf jeden Fall, dass er synchron und weniger umständlich verwendet werden kann und, dass er die Typen der Config kennt. Vielleicht übersehe ich auch einen Nachteil dieser Variante.

Auf jeden Fall sollte nur eine der beiden Varianten verwendet und die jeweils anderen Aufrufe ersetzt werden.

Verwendungen von `storage.get("config")`:

- [ ] ./src/components/lecture-list/lecture-list.ts:34:    this.storage.get("config").then((config:IConfig) => {
- [ ] ./src/pages/book-detail-view/book-detail-view.ts:65:    this.config = await this.storage.get("config");
- [ ] ./src/pages/persons/persons.ts:135:      let config: IConfig = await this.storage.get("config");
- [ ] ./src/pages/practice/practice.ts:100:    let config: IConfig = await this.storage.get("config");
- [ ] ./src/pages/library/library.ts:40:    this.config = await this.storage.get("config");
- [ ] ./src/pages/app-info/app-info.ts:55:    this.storage.get("config").then((config:IConfig) => {
- [ ] ./src/pages/roomplan/roomplan.ts:217:    let config: IConfig = await this.storage.get("config");
- [ ] ./src/pages/grades/grades.ts:51:    this.config = await this.storage.get("config");
- [ ] ./src/pages/mensa/mensa.ts:105:    let config:IConfig = await this.storage.get("config");
- [ ] ./src/pages/impressum/impressum.ts:28:      this.storage.get("config").then((config:IConfig) => {
- [ ] ./src/pages/news/news.ts:47:    let config: IConfig = await this.storage.get("config");
- [ ] ./src/pages/emergency/emergency.ts:87:    let config:IConfig = await this.storage.get("config");
- [ ] ./src/pages/rooms/rooms.ts:169:    let config: IConfig = await this.storage.get("config");
- [ ] ./src/pages/opening-hours/opening-hours.ts:47:    let config:IConfig = await this.storage.get("config");
- [ ] ./src/pages/transport/transport.ts:58:    let config:IConfig = await this.storage.get("config");
- [ ] ./src/pages/detailed-practice/detailed-practice.ts:22:    let config:IConfig = await this.storage.get("config");
- [ ] ./src/pages/events/events.ts:49:    let config: IConfig = await this.storage.get("config");
- [ ] ./src/providers/web-intent/web-intent.ts:68:    this.config = await this.storage.get("config");
- [ ] ./src/providers/web-intent/web-intent.ts:104:    this.storage.get("config").then((config:IConfig) => {
- [ ] ./src/providers/web-intent/web-intent.ts:158:    this.config = await this.storage.get("config");
- [ ] ./src/providers/web-intent/web-intent.ts:178:    this.config = await this.storage.get("config");

**Comment by lkstnr** [comment]
ConfigProvider scheint eleganter zu sein. 

Evtl. brauchen wir dann die ganze Config gar nicht in den Storage zu speichern, sondern nur die App-Version.

**Comment by weihmann** [comment]
Jup, die müsste dann nicht in den storage, sondern wäre immer in diesem Objekt gespeichert, das direkt importiert wird.

**Comment by alekiy** [comment]
duplicate #657

**Comment by weihmann** [comment]
Hängt auch mit  #664 zusammen. Wenn ich das mit der Session noch in der abstrakten Page unter bekomme, muss man die gar nicht mehr manuell abrufen, weil sie automatisch bei Bedarf (`{requireSession:true}`) geholt würde und dann verfügbar wäre.

**Comment by lkstnr** [comment]
Benutze bei der Ionic 4 Version jetzt den ConfigProvider.
