### ISSUE TITLE
Abstrakte Page 

### ISSUE THREAD

**Issue by weihmann** [University-of-Potsdam-MM/Mobile.UP#664]
Es wäre eine gute Idee, alle Pages von einer abstrakten Page erben zu lassen. So könnte man enorm viel redundaten Code einsparen. Ich habe zum Test mal sowas implementiert.
Diese abstrakte Page besitzt bereits ein paar Methoden, die eigentlich jede Page genauso aufruft. 
Das testen der Netzwerkverbindung klappt schonmal, lediglich das Prüfen der Session will noch nicht so ganz klappen. 
Verwenden kann man diese abstrakte Page auf jeden Fall indem man eine beliebige Page diese extenden lässt. Dann noch im Konstruktor den `super()` Konstruktor aufrufen mit entsprechenden Optionen.

**Comment by lkstnr** [comment]
Ich hab die Abstrakte Seite jetzt mal in den Master übernommen. Das mit der Netzwerkverbindung läuft jetzt darüber und das Seitenmenü lasst sich über die URL ausblenden, wenn man eine Seite direkt irgendwo einbinden möchte (`.../pagename?menu=false`)

Mit der Session schaue ich mal demnächst.
