### ISSUE TITLE
Stundenplan ist um 2 Stunden falsch

### ISSUE THREAD

**Issue by HerrX2000** [University-of-Potsdam-MM/Mobile.UP#688]
Bei mir sind alle meine Kurse um 2 nachhinten gerückt. Auf Puls im Stundenplan werden sie mir richtig angezeigt. Dadurch wird eventuell auch mein 2-wöchiger Kurs 18-22 Uhr nicht angezeigt.

Gerät: Pixel XL

Android: 9

App-Version: 7.1.4 / 6.1.1

**Comment by weihmann** [comment]
Soweit ich das beurteilen kann wurde das bereits behoben und sollte im nächsten Release korrigiert sein. Oder, @lkstnr ?

**Comment by lkstnr** [comment]
Ja, das ist mit dem nächsten Update behoben.

**Comment by alekiy** [comment]
@HerrX2000: Wir werden die überarbeitete Version die Tage veröffentlichen.

**Comment by HerrX2000** [comment]
Danke! Meine App ist heute auf 6.2.1 aktuallisiert worden und der Stundenplan wird jetzt richtig angezeigt.
