### ISSUE TITLE
Leistungsübersicht Tab Bar zu lang

### ISSUE THREAD

**Issue by vabene1111** [University-of-Potsdam-MM/Mobile.UP#689]
Die Tab leiste für Beispielsweise Lehramtsstudenten wird ab einer gewissen breite zu breit für den Bildschirm passst sich jedoch nicht an (siehe screenshot)

![image](https://user-images.githubusercontent.com/6819595/55714120-51bfe900-59f2-11e9-9f9e-63d9bcbc8d71.png)

**Comment by lkstnr** [comment]
Jetzt sollte das Tab-Segment zumindest scrollbar sein. 
ToDo: Aber vielleicht ist ein Auswahlmenü wie in den Einstellungen die bessere Option.
