### ISSUE TITLE
Config wird bei Update nicht aktualisiert

### ISSUE THREAD

**Issue by weihmann** [University-of-Potsdam-MM/Mobile.UP#692]
Beim aktuellen Update wird wohl die `config.json` nicht richtig aktualisiert. Das äußert sich bei mir und einem Kommilitonen so, dass auf dem Home screen bei einigen Modulen statt dem Namen der i18n key gezeigt wird und, dass sich diese Module nicht öffnen lassen. Liegt sicherlich daran, dass sich die Modulnamen geändert haben. Nach einer Neuinstallation ist alles korrekt.

**Comment by lkstnr** [comment]
Ja, das ist mir auch gerade aufgefallen. Wir speichern die Modulliste derzeit im Storage und laden nie die aktualisierte Config. Die `ngOnInit()` der `home.page.ts` müssen wir so umschreiben, dass 

- eventuelle Änderungen bspw. am i18n key berücksichtigt werden
- neu hinzugefügte Pages angezeigt werden (wahrscheinlich sieht niemand die Feedback Page)
- die Favoriten des Users trotzdem erhalten bleiben

**Comment by alekiy** [comment]
Ein ungewöhnliches Feature aber vllt auf dem Startscreen auch Pull-To-Refresh zum manuellen Neuladen der Config verwenden? :P

**Comment by weihmann** [comment]
Wäre eine Lösung, aber dann müsste der Nutzer in einer Situation wie dieser auch wissen, dass er das machen soll. Würde ich jetzt so nicht erwarten. Für mich als Benutzer wäre die App auf den ersten Blick einfach kaputt.

Die aktuellen Favoriten des Nutzers könnte man sich merken, indem man die Namen der favorisierten Pages speichert (Davon ausgehend, dass sich diese nicht ändern). Dann müsste man diese Liste der gemerkten Favoriten beim Neu-Erzeugen der HomePage Module berücksichtigen.
