### ISSUE TITLE
Android Notification Icons werden nicht angezeigt

### ISSUE THREAD

**Issue by vabene1111** [University-of-Potsdam-MM/Mobile.UP#697]
Habe aktuell keine Zeit mir das genauer anzugucken, aber auf android werden, wenn man die app offen hat, die icons in der notification bar oben nicht mehr angezeigt.

Eine mögliche Lösung habe ich hier gefunden, aber wie gesagt keine Zeit gehabt mir das genauer anzugucken https://forum.ionicframework.com/t/android-status-bar-no-icon-shown/113489/5

**Comment by weihmann** [comment]
Danke für den Link, hat direkt funktioniert.
