### ISSUE TITLE
Fontawesome bei build ins Projekt kopieren statt nachladen

### ISSUE THREAD

**Issue by weihmann** [University-of-Potsdam-MM/Mobile.UP#709]
Ich sehe gerade, dass Fontawesome immer nachgeladen wird. Wäre vielleicht schöner, das direkt aus dem `node_modules` Ordner zu kopieren, statt es jedesmal nachzuladen.

**Comment by alekiy** [comment]
Bitte gleich prüfen mit Chrome Network welche externe Ressourcen ggf. ebenfalls nachgeladen werden.

**Comment by weihmann** [comment]
Es wurde nur noch Fontawesome nachgeladen - und das jetzt auch nicht mehr.
