### ISSUE TITLE
Status-Bar Icons fehlen

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#710]
> Liebes Mobile.UP-Team,
> 
> die App zeigt bereits seit langer Zeit keine StatusBar-Icons an (siehe 
> Screenshot). Vielleicht hilft euch 
> https://forum.ionicframework.com/t/android-status-bar-no-icon-shown/113489 
> weiter?

**Comment by lkstnr** [comment]
Mh. Ich glaube @weihmann hatte das schon bearbeitet, vgl. #697

**Comment by alekiy** [comment]
@ItsNotYou
