### ISSUE TITLE
app-info.page.html - benutzte Packages aus packages.json auslesen

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#717]
Derzeit ist es hardgecoded.

**Comment by weihmann** [comment]
Ich habe jetzt merhmals versucht, das mittels der `angular.json` als asset direkt beim Build mitzukopieren, aber das will nicht funktionieren. Vielleicht kann man nichts aus dem Projekt-Root-Verzeichnis als asset verwenden? Hab dazu nicht viel gefunden. Ist aber ärgerlich, weil das die einzige vernünftige Lösung wäre.

**Comment by weihmann** [comment]
Eine andere Möglichkeit wäre, einfach die `package.json` aus dem master des Repos zu holen?
