### ISSUE TITLE
400 Bad Requests /endpoints/token

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#718]
Auf dem API-Manager kommen viele Bad Requests mit dem Endpoint /endpoints/token an.
Kann dies an der App oder einer alten Version liegen?

Ich denke wir hatten / haben das Problem wenn wir etwas mit einem falschen Token anfragen oder?

**Comment by lkstnr** [comment]
Bei mir kommt ohne Private Browsing: 

> "Refresh token is expired."

Wahrscheinlich wurde die App in der Klausurenphase öfter nicht genutzt? Ich probiere jetzt den Nutzer einmal automatisch erneut einzuloggen, ansonsten wird ein Hinweis eingeblendet und auf die Login-Seite weitergeleitet.

Oder gibt es einen besseren Weg, den Refresh-Token zu erneuern?
