### ISSUE TITLE
Sensibler Bereich von Sliding Items erhöhen

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#719]
Bei Tests auf einem Android-Gerät ist mir aufgefallen, dass man sehr genau und in einem sehr kleinen Bereich an der Seite wischen muss, so dass sich das "Kontextmenu" bspw beim Markieren von Bibliothekseinträgen als Favoriten öffnet.
Kann man hier die Genauigkeit anpassen, so dass man ggf. auch weiter in der Mitte wischen kann?

**Comment by lkstnr** [comment]
Ich hab dafür keine zufriedenstellende Lösung gefunden.

**Comment by alekiy** [comment]
- https://stackoverflow.com/questions/43797762/ionic3-slides-swipe-sensitivity
- http://idangero.us/swiper/api/

Das vielleicht?

**Comment by lkstnr** [comment]
<ion-slides> ist nochmal was ganz anderes als <ion-item-sliding>. 

<ion-slides> benutzen wir bspw. für die rotierenden Mensa-Icons, da ist jedes Icon eine eigene <ion-slide>

**Comment by lkstnr** [comment]
@weihmann Kannst du das auf deine Gerät reproduzieren? Auf den Geräten, die ich getestet habe, kann man überall im Item swipen.

**Comment by weihmann** [comment]
> @weihmann Kannst du das auf deine Gerät reproduzieren? Auf den Geräten, die ich getestet habe, kann man überall im Item swipen.

Nein, kann ich nicht. Bei mir funktioniert das Sliding zum Öffnen des Kontextmenüs im ganzen Item.
