### ISSUE TITLE
Zurück-Button bei offenem CampusMap Modal

### ISSUE THREAD

**Issue by weihmann** [University-of-Potsdam-MM/Mobile.UP#720]
- Situation: Modal eines Features der CampusMap ist geöffnet
- Input: Back-Button wird gedrückt
- Erwartung: Modal wird geschlossen, Page bleibt offen
- Realität: 
  - Unter Android wird die Page samt Modal geschlossen
  - Im Browser wird die Page geschlossen, das Modal bleibt aber im Vordergrund. Durch Schließen des Modals stellt man dann fest, dass man auf der HomePage gelandet ist

**Comment by lkstnr** [comment]
Für Android hab ich das letztens behoben d423b41ac7c26c2832b67a1197e4ac83ebb2b0ab (noch nicht im master).
