### ISSUE TITLE
Filter leer am Wochenende

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#723]
Getestet am Wochenende mit leerem Essenplan.
Startet die Mensa in Griebnitzsee und klickt man dann auf Filter (Zeile oder Button) wird ein leeres Filterfeld (siehe Screenshot) angezeigt. Beim Wechseln auf einen anderen Standort funktioniert es dann.

![IMG_0028](https://user-images.githubusercontent.com/2682987/62441839-02968480-b756-11e9-8c36-6d71df48108d.PNG)

**Comment by lkstnr** [comment]
Das liegt daran, dass die Filter dynamisch aus der Mensa-API Response generiert werden. Ich habe das Filter-`ion-select` jetzt `disabled`, wenn es keine Filter gibt, aus denen man auswählen kann
