### ISSUE TITLE
Lageplan: PC-Pools hinzufügen

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#729]
User-Feedback
> PC Pools nicht mehr eingezeichnet und werden per suche nicht gefunden

**Comment by weihmann** [comment]
Es sind wahrscheinlich diese gemeint:

https://www.uni-potsdam.de/de/zim/beratung-hilfe/it-arbeitsplaetze.html

**Comment by weihmann** [comment]
@Beschorner es sollen nur die öffentlich zugänglichen Computerpools, also die des ZIMs, im Lageplan vorhanden sein.

**Comment by Beschorner** [comment]
2a8f083c5640990b6a9bfcbe971b6b1dc19ec54f fügt die [ZIM-Computer-Pools](https://www.uni-potsdam.de/de/zim/beratung-hilfe/it-arbeitsplaetze.html) zur Beschreibung der Gebäude hinzu.

Evtl. wäre es sinnvoll Häusern Such-Schlagwörter außerhalb des Namens und der Beschreibung zuweisen zu können. Z.B. werden Computer-Pools auf den Seiten der Uni auch "IT-Arbeitsplätze", "PC-Pools" oder "Rechnerpools" genannt.
Auf diese Weise könnte man auch oft gebrauchte Abkürzungen und Synonyme hinzufügen.

**Comment by weihmann** [comment]
Gute Idee. Könnte man über ein zusätzliches optionales Feld "tags" oder so realisieren. Kuck ich mir an.

**Comment by weihmann** [comment]
Ist gemerged.

Für Tags siehe #795.
