### ISSUE TITLE
Performance auf (älteren) Geräten verbessern

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#732]
> Seit dem Update vor einigen Monaten sehr unzuverlässig. Hängt sich oft auf. Funktioniert die App finde ich sie sehr praktisch. (Android 6.0 | HUAWEI VNS-L31)

**Comment by alekiy** [comment]
- Ticketsystem prüfen und Feedbacks in Datenbank
