### ISSUE TITLE
Leerer Stundenplan

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#737]
> Fehlermeldung gibt es keine, es erscheint der Stundenplan ohne Inhalt. [...] Ich studiere Lehramt Primar Inklusion (LPI)

**Comment by lkstnr** [comment]
Bei den beiden Leuten, die sich zurückgemeldet haben kommt von der PULS-Schnittstelle tatsächlich `no user rights` zurück (beim Call `pulsGetStudentCourses`). An PULS weiterleiten?

**Comment by alekiy** [comment]
Jawoll. Schicke mir mal die Benutzernamen per E-Mail zu. Dann muss PULS schauen.
