### ISSUE TITLE
Bibliothekssuche funktioniert nicht mehr

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#740]
Scheint im Backend etwas umgestellt worden zu sein. Läuft somit in keiner Version der App mehr. 

`recordSchema: 'mods'` wird anscheinend nicht mehr unterstützt

Response nach Suchanfrage
> Record not available in this schema

```
<zs:record><zs:recordSchema>info:srw/schema/1/diagnostics-v1.1</zs:recordSchema><zs:recordPacking>xml</zs:recordPacking><zs:recordData><diagnostic xmlns="http://www.loc.gov/zing/srw/diagnostic/">
 <uri>info:srw/diagnostic/1/67</uri>
 <message>Record not available in this schema</message>
</diagnostic></zs:recordData><zs:recordPosition>1</zs:recordPosition></zs:record>
```

**Comment by lkstnr** [comment]
https://verbundwiki.gbv.de/display/VZG/SRU

Schemen `dc`, `marcxml`, `picaxml` liefern eine korrekte Response zurück, sind aber extrem unhandlich / unübersichtlich.

**Comment by alekiy** [comment]
https://knowledge.exlibrisgroup.com/Aleph/Knowledge_Articles/SRU-Search_ends_up_with_error_%22Record_not_available_in_this_schema%22

**Comment by lkstnr** [comment]
Funktioniert wieder, war anscheinend nur vorübergehend (?)
