### ISSUE TITLE
Kalenderexport unvollständig und Kalenderauswahl anbieten

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#749]
> leider ist die Funktion Export: Stundenplan unvollständig angelegt. Es wäre sinnvoll an dieser Stelle den Dialog:Kalenderauswahl zu ergänzen, so kann der Inhalt auch in einen synchronisierten Kalender exportiert werden. Derzeit wird auf dem iPhone (iOS 13.x, aktuellste)nur ein lokaler Kalender angelegt.

**Comment by lkstnr** [comment]
Haben wir einen Testaccount, der auch Veranstaltungen belegt hat? Da ich selbst keine Veranstaltungen habe, kann ich das mit dem unvollständigen Export nicht testen.

Kalenderauswahl ist bestimmt machbar.

**Comment by alekiy** [comment]
@lkstnr Leider haben wir keinen Testaccount der Veranstaltungen belegt. Müssen wir immer manuell anfragen.
