### ISSUE TITLE
Einheitliches Verhalten Umgang mit "Netzwerkfehlern"

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#751]
Am Wochenende war der API-Manager nicht erreichbar. Als Fehler kam "Netzwerkfehler".
Daraus ergeben sich zwei Punkte:

- [x] Beim Login wird der Fehler nicht abgefangen, stattdessen erscheint Benutzername / Passwort falsch.
- [x] Bei der Bibliothekssuche und beim Nahverkehr erscheint nicht gleich wie bei den anderen Seiten eine Fehlernachricht, erst nach der Interaktion. Vermutlich wird hier die Konnektivität anders geprüft.

**Comment by lkstnr** [comment]
Es wird nun auf allen Seiten eine Hinweis-Box angezeigt, der unterscheidet zwischen "Keine Internetverbindung" und "Der Dienst ist derzeit nicht verfügbar". 

Nur bei der Login-Seite wird man zurück zum Startbildschirm geschickt, wenn man keine Internetverbindung hat.
