### ISSUE TITLE
Einstellungen öffnet sich im Hintergrund

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#752]
> The problem ... the menu bar in the side doesn't close once opened. So if I want to access settings, the menu bar opens it in the background but I am not able to actually access the settings page because the menu bar keeps blocking it

![Screenshot_20191027-091923](https://user-images.githubusercontent.com/2682987/67669657-a1580900-f972-11e9-995d-6634f8b3c2d9.jpg)

**Comment by lkstnr** [comment]
@weihmann Kannst du das reproduzieren? Bei mir funktioniert das auf allen Platformen..

**Comment by weihmann** [comment]
Nein, passiert bei mir nicht. Kann mir jetzt aber auch nicht vorstellen, an was das liegen könnte. Mit dem Menü machen wir ja nichts besonderes, also keine Hacks oder dergleichen, die da dazwischenfunken könnten, oder?
