### ISSUE TITLE
Öffnungszeiten PH off

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#764]
PH steht für gesetzliche Feiertage. PH off entsprechend, dass an den Tagen die Einrichtungen zu haben.
Am 06.1 ist ein regionaler Feiertag der jedoch nicht für Brandenburg gilt.
Wo kann die Liste der gesetzlichen Feiertage angepasst werden?

**Comment by weihmann** [comment]
Sollte laut [opening_hours](https://github.com/opening-hours/opening_hours.js/tree/master#holidays) eigentlich bereits berücksichtigt werden.

Das [Nominatim-Objekt](https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=52.4038&lon=13.0078) wird korrekt erzeugt. Das heißt, die eingebundene opening_hours-library sollte eigentlich wissen, in welchem Bundesland man sich befindet und den opening-hours-string entsprechend auswerten.
