### ISSUE TITLE
Haus 4 Raum 0.22 liegt im Mitarbeiterbereich und ist nicht für Studierende zugänglich

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#766]
![Screenshot_20200204-145818_MobileUP](https://user-images.githubusercontent.com/33331864/73931030-e11a7f00-48d7-11ea-8eed-f2e6d114f4f1.jpg)

**Comment by alekiy** [comment]
Raum wurde der Blacklist von roomsAPI hinzugefügt.
