### ISSUE TITLE
Banner-Werbung für das Campus Festival 2020 

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#767]
> Sehr geehrtes Mobile UP Team,
wir wollten fragen ob es vielleicht möglich wäre, Banner oder Werbung für 
Uni eigene Veranstaltungen in die App einzubinden. Wir denken da besonders an das Campus Festival 2020 .....

**Comment by alekiy** [comment]
Eine Einbindung von Werbung als Kachel, Banner oder Toast ist aktuell nicht gewünscht. Eine Antwort erfolgte. Bei ähnlichen Anfragen auf das Eintragen in den Veranstaltungskalender verweisen. Da es ggf. später mal relevant sein könnte, schiebe ich es in den Backlog als Feature Request.
