### ISSUE TITLE
Ionic 5 & Angular 9

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#771]
https://ionicacademy.com/upgrade-your-app-to-ionic-5/

Vieles war anscheinend schon vorher deprecated, weshalb ich einige der Änderungen schon gemacht habe. Scheint weniger Änderungen zu benötigen im Vergleich zum Ionic 3 -> 4 Upgrade.

**Comment by weihmann** [comment]
Kriegen wir das in das 6.4 Release noch mit rein?

**Comment by lkstnr** [comment]
Sollte möglich sein, komme aber erst Dienstag dazu.
