### ISSUE TITLE
Inkonsistente Anzeige der Öffnungszeiten

### ISSUE THREAD

**Issue by weihmann** [University-of-Potsdam-MM/Mobile.UP#774]
Heute (Dienstag) wird angzeigt, dass diese Stelle dann öffnet, wenn sie eigentlich geschlossen hat. Passiert sowohl in der App als auch in der Webversion. @lkstnr Weißt du woran das liegen könnte?

![Screenshot_2020-05-05 Mobile UP https mobileup uni-potsdam de ](https://user-images.githubusercontent.com/33127365/81067520-120e4e00-8edf-11ea-8465-97253505a092.png)

**Comment by lkstnr** [comment]
Sobald ein Kommentar existiert, wird es nicht mehr als "offen/geschlossen" ausgewertet, sondern als "unbekannt". Ich schau mir mal an, wie wir das am besten lösen.

Derzeit überprüft er nur, ob "offen" ist und der Fall "unbekannt" wird nicht berücksichtigt.

**Comment by weihmann** [comment]
Ah, okay. Vielen Dank!

**Comment by lkstnr** [comment]
Tatsächlich wird es nur zu "unbekannt" ausgewertet, wenn die Öffnungszeiten in der OpeningsGui nicht eindeutig angegeben sind. Ich hab das jetzt mal geändert, sodass es auch ohne App Update korrekt angezeigt wird.

Ich hab den "unbekannt" Status trotzdem mit in die App genommen, damit in Zukunft in solchen Fällen keine falschen Infos mehr angezeigt werden.
