### ISSUE TITLE
Connection-Indicator funktioniert nicht

### ISSUE THREAD

**Issue by weihmann** [University-of-Potsdam-MM/Mobile.UP#777]
Dieser Connection-Indicator funktioniert zumindest auf meinem Gerät nicht. Er zeigt immer "Keine Internetverbindung", auch wenn das Gerät sicher Internet hat. @lkstnr Sollte das funktionieren?

**Comment by lkstnr** [comment]
Ja, das hat mal funktioniert. Bei mir klappt es aber auch nur noch im Browser, auf meine Handy ist es genau andersherum – es wird nie etwas angezeigt, selbst wenn keine Verbindung da ist.

Ich guck mir das morgen an.
