### ISSUE TITLE
Events-RSS-Feed integrieren

### ISSUE THREAD

**Issue by weihmann** [University-of-Potsdam-MM/Mobile.UP#782]
Der nun wieder verfügbare Events-RSS-Feed könnte entweder in einer eigenen Page abgeholt werden oder in der NewsPage untergebracht werden.

**Comment by weihmann** [comment]
Die URL des Events feeds ist `https://apiup.uni-potsdam.de/endpoints/newsAPI/news`

**Comment by lkstnr** [comment]
@weihmann Gibt es hier eine Möglichkeit nur zukünftige Events abzurufen? Ich kriege derzeit circa 3700 Events zurück, von denen einige aus 2016 sind.

**Comment by weihmann** [comment]
> @weihmann Gibt es hier eine Möglichkeit nur zukünftige Events abzurufen? Ich kriege derzeit circa 3900 Events zurück, von denen einige aus 2016 sind.
> 
> EDIT: `/newsAPI/events` ist doch aktuell, oder?

Ja, `events` ist aktuell. Es existiert seit kurzem die Funktion `events/from/{date}`. Diese gibt die Events seit `{date}` zurück, wobei `{date}` einfach die Unix-Time in Sekunden ist.
