### ISSUE TITLE
Tipps & Tricks (FG)

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Mobile.UP#99]
- [x] Anleitung Webmail
- [x] Bedeutung Raumnummern
- [x] Hinweis Mensakarte
- [x] Begrüßungsgeld
- [x] Icon für den Link im Hauptmenü

**Comment by alekiy** [comment]
- Tipps & Tricks bitte auch in den master mergen
- Inhalte als JSON pflegbar machen und analog zu Öffnungszeiten auf Server hinterlegen und von dort abrufen

**Comment by ItsNotYou** [comment]
Begrüßungsgeld gibt es nicht mehr

**Comment by ItsNotYou** [comment]
@Clickmari Wir brauchen noch ein Icon für den Hauptmenü-Link

**Comment by ItsNotYou** [comment]
Matze hat Icons gebastelt.
